coverage:
  notify:
    gitter:
      default:
        url: secret:qpIrkrrjsmtaTWW3Hyf8doJtNwtL1fS1wWw5tpkh+EeonHLiX5oYCoQqbndNyAy9WYJ+3gwSSGanG0W9LQNAtr2aMyHXRUcuEnw0c3ljCaAiiVnPgXmq7W+53i/qOAfB
        threashold: 1%
  status:
    project:
      default:
        threshold: 1%
comment:
  behavior: default
  require_changes: true
